#!/bin/sh
#
#	Create by Voli

#:::::: Fix beallitasok :::::::
HOST="http://localhost:8080/api/v2/torrents/info"
#:::::: Beallitasok :::::::::::
    Title=$TITLE 			## A globális cimke
    [ -n "$1" ] && Title="$1" 		## Parancssorból is kaphatja

    curl -s ${HOST}  | jq -r '.[].state' | sort | uniq -c | awk '{print $2, $1}'

exit 0
