#!/bin/sh
#	Created by Volarics Istvan (Voli)

cd /tmp

Ver=$( rslsync --help|grep "Resilio Sync"|sed 's/Resilio Sync//g; s/ \+//g; s/(/./g; s/).*//g; ' )

rm /tmp/.sync/* ; rmdir /tmp/.sync

echo -n "${Ver}"
