#FROM alpine:edge
FROM alpine:3.22

LABEL 	maintainer="Volarics István volaricsi@volarics.hu" 		\
	url="https://github.com/VolaricsI/docker-image"

ENV PUID=2002 PGID=2002 UMASK=002 TIME_ZONE=Europe/Budapest 


		# A szükséges programok; A végén törlöm ami már nem kell
RUN apk update && apk upgrade 	\
	# A futtató környezet:
	&& apk add --no-cache qbittorrent-nox curl jq 	\
	# Csak a telepítéshez kellenek
	&& apk add runit tzdata mc git 	\
	# ami már nem kell, (a tzdata törlése később: a timezone beállítása után kell)
#    && apk del git mc 		\
	# Az alap könyvtárak
	&& mkdir -p /defaults /config /downloads

COPY defaults /defaults

RUN /defaults/configure.sh && /defaults/configure-qbittorrent.sh && /defaults/configure-www.sh


## dht/torrent ports; WebAdmin; 
EXPOSE 6881 6881/udp 8080

## Konfigok helye; ide kerülnek a letöltések
VOLUME /config /downloads

#HEALTHCHECK --interval=5m --timeout=10s  CMD healthcheck


CMD ["/start.sh"]
