#!/bin/sh
#
#	Create by Voli

#:::::: Fix beallitasok :::::::
#:::::: Beallitasok :::::::::::
	transmission-remote -l | awk 'NR>1 && $0 !~ /Sum:/ {count[$9]++} END {for (s in count) print s, count[s]}'
exit 0
