#!/bin/bash

docker image prune -f

DIR=$(pwd)

ls  |while read a; do
    [ ! -d ${a} ] && continue

    echo ">>>>>>>>>>>>>>>>>${a}/Build<<<<<<<<<<<<<<<<<<<"
    cd ${a}
    pwd
    ./Build
    cd $DIR
done
