#!/bin/sh

    docker image ls |grep -v -e "^REPOSITORY" -e "<none>" |grep "^volaricsi/" |sed 's/ \+/:/ ; s/ .*// ' |sort |while read f ; do
	echo "======================= $f ================="
	docker push "$f"

    done


