#!/bin/sh

IMAGE_NAME=volaricsi/resilio


NOCACHE="--no-cache"

ALAP=$( echo $0|sed 's/.*_//g;' )

if [ ! -z ${ALAP} ]; then
    A_tag=":${ALAP}"; A_file="_${ALAP}"; A_ver="${ALAP}_"
fi
    ## Nézük meg, hogy az alap image is legyen a legfrissebb
if [ ! -z ${NOCACHE} ]; then
    docker image pull frolvlad/alpine-glibc
    docker image pull ubuntu
fi

echo 	docker image build ${NOCACHE} --tag ${IMAGE_NAME}${A_tag} -f Dockerfile${A_file} .
	docker image build ${NOCACHE} --tag ${IMAGE_NAME}${A_tag} -f Dockerfile${A_file} .
	if [ $? -ne 0 ]; then
		echo Sikertelen build.....
		exit 1
	fi

	echo 	docker run --rm ${IMAGE_NAME}${A_tag} verzio
	Ver=$(  docker run --rm ${IMAGE_NAME}${A_tag} verzio )
	if [ $? -ne 0 ]; then
		echo Sikertelen verzió meghatározás.....
		exit 1
	fi

echo	docker tag ${IMAGE_NAME}${A_tag} ${IMAGE_NAME}:${A_ver}${Ver}
	docker tag ${IMAGE_NAME}${A_tag} ${IMAGE_NAME}:${A_ver}${Ver}

	docker tag ${IMAGE_NAME}${A_tag} ${IMAGE_NAME}:latest
