FROM ubuntu:25.04
#FROM ubuntu:22.04
LABEL Maintainer="Volarics István volaricsi@gmail.com"

	## Ekkor a csomagban léző rutorrent-et teszi fel és nem a github-os verziót
ENV RUTORRENT_PKG=" rutorrent "

	##Ezek a programok kellenek még a plugin-eknek; ha szükségét érzed vedd ki a commentet
ENV PLUGIN_PRG_LIST=" ffmpeg sox mediainfo unrar "
#ENV PLUGIN_PRG=$PLUGIN_PRG_LIST

ENV TIME_ZONE=Europe/Budapest

RUN export DEBIAN_FRONTEND=noninteractive 	\
		# Ezek kellenek a futáshoz
    && apt update && apt -y upgrade && apt install -y runit rtorrent php-fpm nginx 	curl 	\
		# Ami csak a telepítéshez kellenek
    && apt install -y tzdata git mc libxmlrpc-core-c3-dev net-tools	\
		# A ruTorrent ha nem csomagból raktad fel
    && cd /var/www && git clone https://github.com/Novik/ruTorrent.git 	



##&& cp $( find / -iname chpst )  /usr/sbin/chpst && cp /usr/bin/xmlrpc /usr/sbin 	
#RUN apt install -y tzdata git mc libxmlrpc-core-c3-dev 
##&& cp $( find / -iname chpst )  /usr/sbin/chpst && cp /usr/bin/xmlrpc /usr/sbin 	\


#    && ln -nf /usr/share/zoneinfo/$TIME_ZONE /etc/localtime && echo $TIME_ZONE >/etc/timezone fi 	
RUN ln -nf /usr/share/zoneinfo/$TIME_ZONE /etc/localtime && echo $TIME_ZONE >/etc/timezone fi 	

		# Ideiglenesen kellet programok eltávolítása
##    && apt remove --purge -y git runit libxmlrpc-core-c3-dev 	\
##		# A szügségtelen programok, melyek az alap image-ben vannak
##    && apt remove --purge -y manpages manpages-dev openssl publicsuffix xz-utils geoip-database bzip2 krb5-locales 	\
##    && apt autoremove --purge -y && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* && rm -rf /var/cache 	\
##	# Az alap könyvtárak
##    && mkdir -p /defaults /config /downloads
##    && ln -nf /usr/share/zoneinfo/$TIME_ZONE /etc/localtime && echo $TIME_ZONE >/etc/timezone fi 	\

RUN mkdir -p /defaults /config /downloads


COPY defaults /defaults

RUN /defaults/configure.sh
RUN /defaults/configure-munin.sh
RUN /defaults/configure-rutorrent.sh
RUN /defaults/configure-runit.sh

## WebAdmin, dht, data ports
EXPOSE 80 6881/udp 51413

## Konfigok helye; A letöltések helye
VOLUME /config /downloads

# Run the start script on boot.
CMD ["/start.sh"]
