		## Mert ebben van a 0.9.8-r0 STABIL rtorrent és ez a mainstream
#FROM alpine:edge
#FROM alpine:3.22
FROM alpine:3.20

LABEL 	maintainer="Volarics István volaricsi@volarics.hu" 		\
	url="https://github.com/VolaricsI/docker-image"

		## Személyre szabott beállítások
ENV PUID=2002 PGID=2002 UMASK=002 TIME_ZONE=Europe/Budapest

ENV DIR_RUT=/var/www/ruTorrent

		# A szükséges programok; A végén törlöm ami már nem kell; ffmpeg-től a plugin-eknek kellenek
RUN apk update && apk upgrade 	\
	# A futtató környezet: rtorrent, web admin; modulok
    && apk add --no-cache runit rtorrent 	nginx php php-fpm php-json 	xmlrpc-c-tools	\
	# A ruTorrent Plugin-jeihez kellő programok. van ami a configure-rutorrent.sh-ban van
    && apk add php83-xml php83-session php83-dom php83-fileinfo curl ffmpeg sox mediainfo	\
	# A munin plugin-ek hibátlan működéséhez kell
    && apk add perl 										\
	# Csak a telepítéshez kellenek
    && apk add git tzdata mc 									\
	# A ruTorrent
    && cd /var/www && git clone https://github.com/Novik/ruTorrent.git 				\
	# ami már nem kell, (a tzdata törlése később: a timezone beállítása után kell)
#    && apk del git mc 										\
	# Az alap könyvtárak
    && mkdir -p /defaults /config /downloads

COPY defaults /defaults

RUN	/defaults/configure.sh
RUN	/defaults/configure-munin.sh
RUN	/defaults/configure-rutorrent.sh
RUN	/defaults/configure-runit.sh
RUN	/defaults/configure-vege.sh

## dht; data ports; WebAdmin; [ távirányító/management (xmlrpc) port (5000) már nem szükséges kivezetni ]
EXPOSE 6881/udp 51413 80

## Konfigok helye; ide kerülnek a letöltések
#VOLUME /config /downloads

HEALTHCHECK --interval=5m --timeout=10s  CMD healthcheck

# Az entrypoint beállítása
ENTRYPOINT ["/entrypoint.sh"]

CMD ["/start.sh"]
