#!/bin/bash
#	Created by Volarics Istvan (Voli)

xmlrpc localhost d.multicall "main"  "d.get_base_filename="  "d.get_message="	|grep "Index [ 0-9]\+ String:"	\
	|sed "s/^.* String: //g;  "	\
	|while read a; do
		read b;
		if [ "${b}" == "''" ]; then continue; fi
		echo "${a} ==> ${b}"
done
