#!/bin/sh
#	Created by Volarics Istvan (Voli)

Ver=$( deluged --version|grep "deluged:"|sed 's/deluged://g; s/ \+//g; s/ \+//g; s/\r.*//g; ' )
BDate=$( cat /defaults/BuildDate.txt )

echo -n "${Ver}_${BDate}"
