#!/bin/sh
#	Created by Volarics Istvan (Voli)

DIR=/var/www/ruTorrent				# ruTorrent helye
INIFILE=$DIR/conf/plugins.ini

DEFAULT=" mediainfo screenshots spectrogram unpack "

Clear(){						#Alap állapotba hozzuk
    cp /defaults/plugins.ini $INIFILE
    echo -e "\n\n;; Kitiltott plugin-ek:\n" 	>>$INIFILE
}

Insert(){
    while [ ".$1" != "." ]; do
    echo "[$1]  enabled = no" 	>>$INIFILE
    [ ".$1" = ".all"     ] && Clear && Insert $( ls $DIR/plugins |sort )
    [ ".$1" = ".default" ] && Clear && Insert $DEFAULT
    shift;
    done
}

	Clear
	Insert $*

supervisorctl restart nginx	>/dev/null
