#!/bin/bash

IMAGE_NAME=volaricsi/resilio
Date=$( date +%Y-%m-%d )


docker image build --tag ${IMAGE_NAME} --tag ${IMAGE_NAME}:${Date} .
Ver=$( docker run --rm  -t ${IMAGE_NAME} verzio )
docker tag ${IMAGE_NAME} ${IMAGE_NAME}:${Ver}


docker push ${IMAGE_NAME}:${Date}
docker push ${IMAGE_NAME}:${Ver}
docker push ${IMAGE_NAME}
