# Sets up a Resilio server with management ports.

FROM ubuntu
MAINTAINER Volarics István volaricsi@gmail.com

ENV TIME_ZONE=Europe/Budapest

# Kell a start.sh-nak mivel innen tudja, hogy más programok kezelit a felhasználókat.
ENV ALAP=ubuntu

# Install required packages.: chpst program, and resilio
RUN export DEBIAN_FRONTEND=noninteractive && apt update && apt upgrade -y 	\
    && apt install -y wget runit tzdata && cp /usr/bin/chpst /bin/chpst 	\
    && ln -nf /usr/share/zoneinfo/$TIME_ZONE /etc/localtime && echo $TIME_ZONE >/etc/timezone 	\
    && cd /tmp && wget --quiet https://download-cdn.resilio.com/stable/linux-x64/resilio-sync_x64.tar.gz 	\
    && tar xvzf resilio-sync_x64.tar.gz && cp rslsync /usr/bin/ 	\
    && apt remove --purge -y wget runit && apt autoremove --purge -y && apt clean 	\
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* 	\
    && mkdir -p /defaults /config /downloads

COPY defaults /defaults

# Add the start script. Create example config
RUN cd /defaults/ && chmod +x * && mv start.sh / && mv * /usr/bin/

# Expose the deluge control port and data port.
EXPOSE 55555 8888

# Setup volumes.
VOLUME /config /downloads

# Run the start script on boot.
CMD ["/start.sh"]
