#!/bin/sh
#
#	Create by Voli

#:::::: Fix beallitasok :::::::
#:::::: Beallitasok :::::::::::
#:::::: Ellenorzesek ::::::::::

    if [ -x /usr/bin/apt ]; then 	## Ubuntu alap
	UJsomagSzam=$( apt update 2>/dev/null |grep "apt list --upgradable" 2>/dev/null |sed 's/ package.*//; s/ csomag.*// ' )
	Ret=$?
    fi

    if [ -x /sbin/apk ]; then 		## Alpine alapon
	apk update 	>/dev/null 2>&1
	UJsomagSzam=$( apk version -v -l '<' -l '?' |grep -v "^Installed:" |grep -c "." )
	Ret=$?
    fi

    [ $Ret -ne 0 	] && exit $Ret 		## Ha hiba történt
    [ -z "$UJsomagSzam" ] && exit 0 		## Ha nincs frissítendő csomag

    [ -z "$1" ] && echo "Az image: deluge_1.3.x."
    [ -n "$1" ] && echo "A(z) $1 contenerben $UJsomagSzam csomagot lehet/kell frissíteni..."
    [ -x /usr/bin/apt ] && apt list --upgradable 2>/dev/null
    [ -x /sbin/apk    ] && apk version -v |grep -v -e " = " -e "^Installed:"
    exit 0
