#!/bin/sh

IMAGE_NAME=volaricsi/rtorrent
BuildParam="--no-cache"

Fordit(){

echo "**************** $1 ***********************"

    A_tag=":$1"; A_file="_$1"; A_ver="$1_"

echo 	docker image build $BuildParam --tag ${IMAGE_NAME}${A_tag} -f Dockerfile${A_file} .
	docker image build $BuildParam --tag ${IMAGE_NAME}${A_tag} -f Dockerfile${A_file} .
	if [ $? -ne 0 ]; then
		echo Sikertelen build.....
		exit 1
	fi

	echo 	docker run --rm ${IMAGE_NAME}${A_tag} verzio
	Ver=$( 	docker run --rm ${IMAGE_NAME}${A_tag} verzio )
	if [ $? -ne 0 ]; then
		echo Sikertelen verzió meghatározás.....
		exit 1
	fi

echo	docker tag ${IMAGE_NAME}${A_tag} ${IMAGE_NAME}:${A_ver}${Ver}
	docker tag ${IMAGE_NAME}${A_tag} ${IMAGE_NAME}:${A_ver}${Ver}

	docker tag ${IMAGE_NAME}${A_tag} ${IMAGE_NAME}:${Ver}
	docker tag ${IMAGE_NAME}${A_tag} ${IMAGE_NAME}:latest

}

	Fordit alpine-3.7
	Fordit alpine
	Fordit ubuntu


	docker image ls |grep "${IMAGE_NAME}"
