FROM ubuntu:19.04

LABEL 	maintainer="Volarics István volaricsi@volarics.hu" 		\
	url="https://github.com/VolaricsI/docker-image"

	## Alap telepítésben ezek a modulok majd tiltásra kerülnek, mert nincs mögöttük program (default) vagy hibásan működik: tracklabels
ENV PLUGIN_DEFAULT_TILTVA="screenshots mediainfo spectrogram _cloudflare rss rssurlrewrite  _task unpack create " 	\
	## A hibás plugin-ek tiltása
    PLUGIN_HIBAS=" extsearch tracklabels " 	\
	## Hogy a fentiek tiltva legyenek
    PLUGIN_DISABLE=default 	\
	## Ezen programok telepítése után az összes plugin menni fog
    PLUGIN_PRG_INSTALL=" ffmpeg mediainfo sox unrar procps "

	## Személyre szabott beállítások
ENV PUID=2002 PGID=2002 UMASK=002 TIME_ZONE=Europe/Budapest PLUGIN_DISABLE=default


		# Kell az apt-utils, hogy ne legyenek hibaüzenetek és a kötelező upgrade
RUN export DEBIAN_FRONTEND=noninteractive && apt-get update && apt-get -y install apt-utils && apt-get -y upgrade 	\
		# Ezek kellenek a futáshoz
    && apt-get install -y supervisor runit rtorrent 	nginx php-fpm php-json 	\
		# Csak azért így külön, mert ekkor nem telepítí az apache-ot és ezek amúgy is csak a plugin-ek működéséhez kellenek
    && apt-get install -y php curl php-zip 	\
		# Ami csak a telepítéshez kellenek, illetve az image-ben turkálásra
    && apt-get install -y tzdata git mc	\
		# A ruTorrent nem csomagból rakom fel
    && git clone https://github.com/Novik/ruTorrent.git /var/www/ruTorrent 	\
		# A munin plugin-ek hibátlan működéséhez kell
    && apt-get install -y netbase 					\
		# Ideiglenesen kelletek eltávolítása
    && apt-get remove --purge -y git mc 	\
		# A szügségtelen programok, melyek az alap image-ben vannak
    && apt-get remove --purge -y manpages manpages-dev openssl publicsuffix xz-utils geoip-database bzip2 krb5-locales openssh-client xauth patch less shared-mime-info mc	\
		# A csomagkezelő adatainak tisztítása
    && apt-get autoremove --purge -y && apt-get clean -y && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* /var/cache && mkdir -p mkdir -p /var/cache/apt/archives/partial	\
		# Az alap könyvtárak
    && mkdir -p /defaults /config /downloads

COPY defaults /defaults

RUN /defaults/configure.sh && /defaults/configure-runit.sh && /defaults/configure-rutorrent.sh && /defaults/configure-munin.sh

## dht; data ports; WebAdmin; [ távirányító/management (xmlrpc) port (5000) már nem szükséges kivezetni ]
EXPOSE 6881/udp 51413 80

## Konfigok helye; ide kerülnek a letöltések
VOLUME /config /downloads

# Run the start script on boot.
CMD ["/start.sh"]
