#!/bin/sh

IMAGE_NAME=volaricsi/deluge_1.3.x


NOCACHE="--no-cache"

	## Nézük meg, hogy az alap image is legyen a legfrissebb
	docker image pull ubuntu:18.04


echo 	docker image build ${NOCACHE} --tag ${IMAGE_NAME} -f Dockerfile .
	docker image build ${NOCACHE} --tag ${IMAGE_NAME} -f Dockerfile .
	if [ $? -ne 0 ]; then
		echo Sikertelen build.....
		exit 1
	fi

	echo 	docker run --rm ${IMAGE_NAME} verzio
	Ver=$( docker run --rm  ${IMAGE_NAME} verzio )
	if [ $? -ne 0 ]; then
		echo Sikertelen verzió meghatározás.....
		exit 1
	fi

echo	docker tag ${IMAGE_NAME} ${IMAGE_NAME}:${Ver}
	docker tag ${IMAGE_NAME} ${IMAGE_NAME}:${Ver}

	docker tag ${IMAGE_NAME} ${IMAGE_NAME}:latest
