#!/bin/sh
#	Create by Voli

#:::::: Beallitasok :::::::::::
	IMAGE_NAME="volaricsi/deluge_1.3.x"
	AlapImagek=" ubuntu:18.04 "
	BuildParam="--no-cache"

#:::::: Fuggvenyek ::::::::::::
FV_TAROLO="../Build"
#:::::::: Start :::::::::::::::
    if [ ! -e "$FV_TAROLO" ]; then
        echo "Hiányző file: $FV_TAROLO ($(readlink -f $FV_TAROLO))."
        exit 1
    fi
    . "$FV_TAROLO"
