#!/bin/sh
#	Created by Volarics Istvan (Voli)

TMP_CNF=config

    cd /tmp/
    rslsync --dump-sample-config | grep -v "/\*.*\*/" >$TMP_CNF
    sed -i 's/\/\/ \"listening_port\" : .*/\"listening_port\" : 55555 ,/g; ' 		$TMP_CNF
    sed -i 's/\/\/ \"storage_path\" .*/\"storage_path\" : \"\/config" ,/g; ' 		$TMP_CNF
    sed -i 's/\/\/  \"directory_root\" : .*/\"directory_root\" : \"\/downloads\" ,/g; ' $TMP_CNF

    grep -v -e "^//" $TMP_CNF

    rm -rf .sync $TMP_CNF resilio_dumps
