FROM alpine:edge


LABEL 	maintainer="Volarics István volaricsi@volarics.hu" 	\
	url="https://github.com/VolaricsI/docker-image"


	## Személyre szabott beállítások; TIME_ZONE kell ha nem tudod mi legyen akkor UTC
ENV PUID=2014 PGID=2014 TIME_ZONE=Europe/Budapest


# Csak ebben a tárolóban van a boinc; Install required packages.: a runit-ből csak a chpst kell;
RUN echo "http://nl.alpinelinux.org/alpine/edge/testing" >>/etc/apk/repositories 			\
    && apk update && apk upgrade 									\
    && apk add runit tzdata boinc && cp $( find / -iname chpst ) /usr/sbin/chpst 			\
    && ln -nf /usr/share/zoneinfo/${TIME_ZONE} /etc/localtime && echo "${TIME_ZONE}" >/etc/timezone 	\
    && mkdir -p /defaults /config

COPY defaults /defaults

RUN /defaults/configure.sh

# management port;
EXPOSE 31416

## Konfigok helye; ide kerülnek a letöltések
VOLUME /config

CMD ["/start.sh"]
