#!/bin/sh
#
#	Create by Voli

#:::::: Fix beallitasok :::::::
L1=/tmp/D2_tor.lst
#:::::: Beallitasok :::::::::::
#:::::: Ellenorzesek ::::::::::
	## A [,],& lecserélem mert vezérlő karakterek, vagy mert xml formátumban az &

    rtorrent-get-dir 	|sed 's/\[/./g; s/\]/./g; s/&amp;/./g;' 	>${L1}

    find /downloads -maxdepth 1 -mindepth 1 |sed 's/\[/./g; s/\]/./g; s/\&/./g; ' |while read a; do
	grep  -e "^${a}" ${L1}	>/dev/null && continue
	echo ">>${a}<<"
    done

    rm ${L1} 	2>/dev/null
exit 0
