#!/bin/sh
#
#	Create by Voli

#:::::: Fix beallitasok :::::::
XMLRPC_HOST=127.0.0.1/RPC
L1=/tmp/D2_tor.lst
#:::::: Beallitasok :::::::::::
    Title=$TITLE 			## A globális cimke
    [ -n "$1" ] && Title="$1" 		## Parancssorból is kaphatja

	## A [,],&amp; lecserélem - .(pont)-ra - mert vezérlő karakterek a grep-ben

curl -s --data "<methodCall> <methodName>download_list</methodName> </methodCall>"   "$XMLRPC_HOST" 		\
    |grep "<value><string>[0-9A-F]\+</string></value>" | sed 's|^<value><string>||; s|</string></value>.*||' 	\
    |while read Hash; do
	curl -s --data "<methodCall><methodName>d.base_path</methodName> <params> <param><value><string>$Hash</string></value></param> </params> </methodCall>" "$XMLRPC_HOST" 	\
	    |grep "^<param><value><string>.*</string></value></param>" |sed 's|^<param><value><string>||; s|</string></value></param>.*||'
    done  	|sed 's|\[|.|g; s|\]|.|g; s|&amp;|.|g; ' 	>${L1}

    find /downloads -maxdepth 1 -mindepth 1 |sed 's|\[|.|g; s|\]|.|g; s|&|.|g; /.docker-mount-point/d; /lost+found/d' |while read a; do
	grep  -e "^${a}" ${L1}	>/dev/null && continue

	if [ -n "$Title" ]; then
		echo "A(z) $Title nevű konténer nem használt könyvtárai..."
		    Title=""
	fi

	echo ">${a}<"
    done
    rm ${L1} 	2>/dev/null
exit 0
