#!/bin/sh
#
#	Create by Voli

#:::::: Fix beallitasok :::::::
#:::::: Beallitasok :::::::::::
#:::::: Ellenorzesek ::::::::::

    if [ -x /usr/bin/apt ]; then 	## Ubuntu alap
	UJsomagSzam=$( apt update 2>/dev/null |grep "apt list --upgradable" |sed 's/ package.*//; s/ csomag.*// ' )
	Ret=$?
    fi


    if [ -x /sbin/apk ]; then 		## Alpine alapon
	apk update 	>/dev/null 2>&1
	UJsomagSzam=$( apk version -v |grep -c -v -e " = " -e "^Installed:" )
	Ret=$?
    fi


    [ $Ret -ne 0 ] 	&& exit $Ret 	## Ha hiba történt
    [ -z $UJsomagSzam ] && exit 0 	## Ha nincs frissítendő csomag


    echo "Az image neve: $ImageNeve."
    echo "A(z) $1 imageben $UJsomagSzam csomagot lehet/kell frissíteni..."
    exit 0
