#!/bin/sh

if [ ! -e /config/rtorrent.rc ]; then
    cp /defaults/rtorrent.rc.example 	/config/rtorrent.rc.example
    cp /defaults/rtorrent.rc.example 	/config/rtorrent.rc
fi

    mkdir -p /config/rutorrent_settings /config/watched

    Session_Dir=$( grep -v "#" /config/rtorrent.rc 	|grep "^session.*=" 	|head -1 |sed 's/.*[ =]//' )
    [ -e "${Session_Dir}/rtorrent.lock" ] && rm ${Session_Dir}/rtorrent.lock

	## Így a konzolra mehet a log...
    chown -Rc abc:tty /dev/pts

    umask $UMASK >/dev/null
    chown -Rc abc:abc /config
    HOME=/config
    cd /config/

    exec 2>&1
    exec chpst -u abc /usr/bin/rtorrent -o system.daemon.set=true -o import=/config/rtorrent.rc
