#!/bin/sh

    sv -w5 check php-fpm 	>/dev/null || exit 1 	## A php-fpm nélül nem tud működni
    sv -w5 check rtorrent 	>/dev/null || exit 1 	## rtorrent nélkül nincs értelme

    CONF_FILE="/config/nginx.conf"

    if [ ! -e /config/nginx.conf ]; then
	cp /defaults/nginx.conf.example /config/
	cp /defaults/nginx.conf.example ${CONF_FILE}
    fi

    chown -R -c abc:abc /var/www/*

    exec 2>&1
    exec nginx -c ${CONF_FILE} -g 'daemon off; '
