#!/bin/bash

docker image prune -f

IMAGE_NAME=volaricsi/resilio
Date=$( date +%Y-%m-%d )


docker image build --tag ${IMAGE_NAME} --tag ${IMAGE_NAME}:${Date} .
Ver=$( docker run --rm  -t ${IMAGE_NAME} rslsync --help|grep "Resilio Sync"|sed 's/Resilio Sync//g; s/ \+//g; s/(/./g; s/).*//g;  ' )
docker tag ${IMAGE_NAME} ${IMAGE_NAME}:${Ver}

docker push ${IMAGE_NAME}:${Date}
docker push ${IMAGE_NAME}:${Ver}
docker push ${IMAGE_NAME}
