#!/usr/bin/perl -w
#

my $ip 		= "127.0.0.1";
my $port 	= 5000;

my $line	= "<?xml version=\"1.0\" encoding=\"utf-8\"?>
    <methodCall><methodName>$ARGV[0]</methodName>";

if ( exists $ARGV[1] ) {
    $line = "$line
		<params>
			<param><value><string>$ARGV[1]</string></value></param>
		</params>";
};

    $line = "$line
		</methodCall>";


#my $line	= "<?xml version=\"1.0\" encoding=\"utf-8\"?>     <methodCall><methodName>$Cmd</methodName> <params>     <param><value><string>$Hash</string></value></param> </params>     </methodCall>";


use IO::Socket;

my $llen	= length $line;
my $header	= "CONTENT_LENGTH\000${llen}\000SCGI\001\000";
my $hlen	= length $header;
$line		= "${hlen}:${header},${line}";

    socket( SOCK, PF_INET, SOCK_STREAM, getprotobyname( "tcp" ) );
    connect( SOCK, sockaddr_in( $port, inet_aton( $ip ) ) );

	print SOCK $line; flush SOCK;

	while ( $line = <SOCK> ) {
		next if $line !~ /<value><string>/ ;

		$line =~ s/<param>// ;
		$line =~ s/<value><string>// ;

		$line =~ s/<.*// ;

		print "$line";

	}

    close (SOCK);

exit;
