#!/bin/sh

#    sv -w5 check rtorrent >/dev/null || exit 1 	## rtorrent nélkül nincs értelme

    CONF_FILE="/config/php-fpm.conf"
    if [ ! -e ${CONF_FILE} ]; then
	cp /defaults/php-fpm.conf.example /config/
	cp /defaults/php-fpm.conf.example ${CONF_FILE}
    fi

    [ -e /tmp/php-fpm.sock ] && rm /tmp/php-fpm.sock 		##A régi socket biztossan nem kell

    exec 2>&1
    exec /usr/bin/php-fpm --nodaemonize --force-stderr -y ${CONF_FILE}
