#!/bin/sh
#
#	Create by Voli

DIR=/var/www/ruTorrent/plugins				# ruTorrent helye
INIFILE=/config/rutorrent_settings/plugins.ini

DEFAULT=" mediainfo screenshots spectrogram unpack _cloudflare "

Clear(){						#Alap állapotba hozzuk
    cp /defaults/plugins.ini ${INIFILE} && chown abc:abc ${INIFILE}
    echo -e "\n\n;; Kitiltott plugin-ek:\n" 	>>$INIFILE
}

Insert(){
    while [ ".$1" != "." ]; do
    echo "[$1]  enabled = no" 	>>${INIFILE}
    [ ".$1" = ".all"     ] && Clear && Insert $( ls ${DIR} |sort )
    [ ".$1" = ".default" ] && Clear && Insert ${DEFAULT}
    shift;
    done
}

	Clear
	Insert $*

supervisorctl restart nginx 	>/dev/null
