#!/bin/bash


##docker image prune -f

IMAGE_NAME=transmission

Date=$( date +%Y-%m-%d )

docker image build --tag volaricsi/${IMAGE_NAME} --tag volaricsi/${IMAGE_NAME}:${Date} . || exit 1

Ver=$( docker run --rm  -it volaricsi/${IMAGE_NAME} verzio )
docker tag volaricsi/${IMAGE_NAME} volaricsi/${IMAGE_NAME}:${Ver}

#docker push 	volaricsi/${IMAGE_NAME}:${Date}
#docker push 	volaricsi/${IMAGE_NAME}:${Ver}
#docker push 	volaricsi/${IMAGE_NAME}
