#!/bin/sh
#
#	Create by Voli

#:::::: Fix beallitasok :::::::
#:::::: Beallitasok :::::::::::
#:::::: Ellenorzesek ::::::::::

    if [ -x /usr/bin/apt ]; then 	## Ubuntu alapon
	Result=$( apt update  2>/dev/null )
	Ret=$?
	UJsomagSzam=$( echo "$Result" |grep "apt list --upgradable" |sed 's/ package.*//; s/ csomag.*// ' )
	[ -z "$UJsomagSzam" ] && UJsomagSzam=0
    fi

    if [ -x /sbin/apk ]; then 		## Alpine alapon
	apk update 	>/dev/null 2>&1
	Ret=$?
	UJsomagSzam=$( apk version -v -l '<' -l '?' |grep -v "^Installed:" |grep -v -c -e "^glibc-bin-" -e "^glibc-" )
    fi

    [ $Ret -ne 0 ] 	&& exit $Ret 		## Ha hiba történt

    cd /tmp
    wget --quiet --no-check-certificate -O - "${BtSyncSrc}" |tar xvzf - >/dev/null
    if [ ! -e ./rslsync ]; then
	echo "Sikertelen az új verzió letöltése..."
	exit 1
    fi

    OldVer=$(   rslsync --help|grep 'Resilio Sync'|sed 's/Resilio Sync//g; s/ \+//g; s/(/./g; s/).*//g; ' )
    NewVer=$( ./rslsync --help|grep 'Resilio Sync'|sed 's/Resilio Sync//g; s/ \+//g; s/(/./g; s/).*//g; ' )
    rm -rf ./rslsync ./LICENSE.TXT ./resilio_dumps

    [ $UJsomagSzam -eq 0 ] && [ ".$OldVer" = ".$NewVer" ] && exit 0

    [ -z "$1" ] && echo "Az image: resillio/btsync."
    [ -n "$1" ] && 	echo "A(z) $1 contenerben $UJsomagSzam csomagot lehet/kell frissíteni..."
    [ $UJsomagSzam -ne 0 ] 	&& echo "A(z) $1 contenerben $UJsomagSzam csomagot lehet/kell frissíteni..."
    [ -x /usr/bin/apt ] 	&& apt list --upgradable
    [ .$OldVer = .$NewVer ] 	|| echo "Régi verzió: $OldVer, az új: >>$NewVer<<."
