#!/bin/sh
#
#	Create by Voli

    cd /tmp

    Ver=$( rslsync --help|grep "Resilio Sync"|sed 's/Resilio Sync//g; s/ \+//g; s/(/./g; s/).*//g; ' )

    rm -rf /tmp/.sync

    BDate=$( cat /defaults/BuildDate.txt )

    echo -n "${Ver}_${BDate}"
