#!/bin/bash

if [ ! -e /config/rtorrent/rtorrent.rc ]; then
    mkdir -p /config/web
    mkdir -p /config/rtorrent
    cp /defaults/example_nginx.conf  /config/web/
    cp /defaults/rtorrent.rc.example /config/rtorrent/rtorrent.rc
fi

    Session_Dir=$( grep "session = " /config/rtorrent/rtorrent.rc |sed 's/.*[ =]//g;' )
    mkdir -p ${Session_Dir}
    chown abc:abc -R /config

    if [ -e ${Session_Dir}/rtorrent.lock ]; then
	kill $(cat ${Session_Dir}/rtorrent.lock|sed 's/.*+//g') 	2>/dev/null
	rm ${Session_Dir}/rtorrent.lock
    fi

    umask $UMASK 	>/dev/null
    exec 2>&1

    exec chpst -u abc screen  -D -L  -m /usr/bin/rtorrent -n -o import=/config/rtorrent/rtorrent.rc
